<p>Your Roll: <button href="#" id="reroll" ic-get-from="/a/roll" ic-target="#content" ic-on-beforeSend="insertSmallImages()">Start Over</button></p>
<div id="bigImages" class="bigImages">
<?php for ($i = 0; $i < count($type); $i++): ?>
	<div class="Type">
		<div title="Type: <?= $type[$i]['name']; ?>" class="Image" style="background-image:url(<?= $type[$i]['image']; ?>);"></div>
		<div class="Name"><?= $type[$i]['name']; ?></div>
		<div class="Button">
<?php if ($i == 0): ?>
			<button
			id="rollType" 
			ic-get-from="/a/roll/type" 
			ic-target="#bigImages" 
			ic-swap-style="append" 
			ic-indicator="#type-load" 
			ic-src="/a/roll/type" 
			ic-trigger-on="default" 
			ic-deps="ignore">
				Roll Another
			</button>
<?php endif; ?>
			<i id="type-load" class="lds-dual-ring"></i>
		</div>
	</div>
<?php endfor; ?>
	
<?php for ($i = 0; $i < count($flavor); $i++): ?>
	<div class="Flavor">
		<div title="Flavor: <?= $flavor[$i]['name']; ?>" class="Image" style="background-image:url(<?= $flavor[$i]['image']; ?>);"></div>
		<div class="Name"><?= $flavor[$i]['name']; ?></div>
		<div class="Button">
<?php if ($i == 0): ?>
			<button 
			id="rollFlavor" 
			ic-get-from="/a/roll/flavor" 
			ic-target="#bigImages" 
			ic-swap-style="append" 
			ic-indicator="#flavor-load" 
			ic-src="/a/roll/flavor" 
			ic-trigger-on="default" 
			ic-deps="ignore"> 
				Roll Another
			</button>
<?php endif; ?>
			<i id="flavor-load" class="lds-dual-ring"></i>
		</div>
	</div>
<?php endfor; ?>
	
<?php for ($i = 0; $i < count($twist); $i++): ?>
	<div title="Twist: <?= $twist[$i]['name']; ?>" class="Twist">
		<div class="Image" style="background-image:url(<?= $twist[$i]['image']; ?>);"></div>
		<div class="Name"><?= $twist[$i]['name']; ?></div>
		<div class="Button">
<?php if ($i == 0): ?>
			<button 
			id="rollTwist" 
			ic-get-from="/a/roll/twist" 
			ic-target="#bigImages" 
			ic-swap-style="append" 
			ic-indicator="#twist-load" 
			ic-src="/a/roll/twist" 
			ic-trigger-on="default" 
			ic-deps="ignore">
				Draw Again
			</button>
<?php endif; ?>
			<i id="twist-load" class="lds-dual-ring"></i>
		</div>
	</div>
<?php endfor; ?>
</div>


<div class="verboseDescription" id="Description">
<?php for ($i=0; $i < max(count($type),count($flavor),count($twist)); $i++): ?>
<?php if ($i > 0): ?>
	<hr />
<?php endif; ?>
<?php if (isset($type[$i])): ?>
	<p><?= $type[$i]['verbose']; ?></p>
<?php endif; ?>
<?php if (isset($flavor[$i])): ?>
	<p><?= $flavor[$i]['verbose']; ?></p>
<?php endif; ?>
<?php if (isset($twist[$i])): ?>
	<p><?= $twist[$i]['verbose']; ?></p>
<?php endif; ?>
<?php endfor; ?>
</div>
<div class="shortDescription hidden" id="ShortDesc">
<?php for ($i=0; $i < max(count($type),count($flavor),count($twist)); $i++): ?>
<?php if (isset($type[$i])): ?>
	<p><?= $type[$i]['short']; ?></p>
<?php endif; ?>
<?php if (isset($flavor[$i])): ?>
	<p><?= $flavor[$i]['short']; ?></p>
<?php endif; ?>
<?php if (isset($twist[$i])): ?>
	<p><?= $twist[$i]['short']; ?></p>
<?php endif; ?>
<?php endfor; ?>
</div>
