<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<title><?php echo $title ?></title>

		<!-- Bootstrap -->
		<link rel="stylesheet" href="/css/basic.css" type="text/css">
		<link rel="stylesheet" href="/css/loader.css" type="text/css">
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
		<script>
			!function(f,u,t,h,a,r,k){f.GoogleAnalyticsObject=t;f[t]||(f[t]=function(){
			(f[t].q=f[t].q||[]).push(arguments)});f[t].l=+new Date;r=u.createElement(h);
			k=u.getElementsByTagName(h)[0];r.src=a;k.parentNode.insertBefore(r,k)}
			(window,document,'ga','script','//www.google-analytics.com/analytics.js');
		</script>

		<script src="/js/analytics.js"></script>

	</head>
	<body>
		<div class='headBar'>
			<h1>Futhark Generator</h1>
			<h2><?php echo $version; ?></h2>
		</div>
		<div class='navbar'>
			<div class="navgroup">
				<p><strong>Pages here</strong></p>
				<ul>
					<li>
						<a href="/">
							Roll them bones!
						</a>
					</li>
					<li>
						<a href="/list">
							See all combinations
						</a>
					</li>
					<li>
						<a href="/donate">
							Help keep the site going
						</a>
					</li>
				</ul>
			</div>
			<div class="navgroup">
				<p><strong>Pages elsewhere</strong></p>
				<ul>
					<li>
						<a href="http://www.reddit.com/r/FutharkGenerator/">
							/r/FutharkGenerator
						</a>
					</li>
					<li>
						<a href="http://www.reddit.com/r/FutharkGenerator/comments/35fcg7/php_futhark_generator/">
							Feedback on reddit
						</a>
					</li>
					<li>
						<a href="https://github.com/farfromunique/Generator-1.5/issues/new">
							Feedback on GitHub
						</a>
					</li>
				</ul>
			</div>
			<div class="navgroup">
				Have you heard of <a href="http://parahumans.wordpress.com/">Worm</a>?
				<br />If not, please <a href="http://www.reddit.com/r/FutharkGenerator/comments/35kilh/if_you_havent_read_worm_read_me_first/">read me first!</a>
			</div>
			<div id='hist' class='hist'>
				<span id='endOfHist'>&nbsp;</span>
			</div>
		</div>
		<div class="content" id="content">
			<h2>Donate</h2>
			<p>Hello, friend. This is a fan-made site, and I don't make any money from it. As the notice at the bottom says, this is Wildbow's sandbox we're playing in. However, web hosting (especially when you have a site designed around the concept of many people reloading it) can get a bit expensive. As a result, I am now soliciting donations. If you feel like tossing a few dollars toward keeping this site up and running, please <a href="https://www.nearlyfreespeech.net/contribute/futhark.acwpd.com" target="_blank">click here</a>.</p>

			<p>These donations have been approved by Wildbow, in the following conversation:</p>
				<pre>
					<strong>to Wildbow - Thursday, 14 May 2015</strong><br />
					Hey wildbow, I'm a huge fan, first off. Thanks for giving us worm, pact, and twig! They're all awesome! As I'm sure you're aware, over on <a href="http://www.reddit.com/r/Futharkgenerator">/r/Futharkgenerator</a> we're building a power generator based off of the Worm universe. I have a version of this hosted on my website (Futhark.acwpd.com). Because web hosting isn't free, I'd like to have a donate button to help cover the costs of hosting. It was suggested that I split any donations with you, if I do so.<br />
					My questions for you are: how do you feel about the donate button; do you want a cut; if so, how much of one; how do you green about the generator in general?<br />
					Thanks in advance, Aaron / farfromunique
				</pre>
				<pre>
					<strong>from Wildbow - Thursday, 14 May 2015</strong><br />
					Shoot, thought I replied before.<br />
					This is the sort of thing that gets really awkward, because I want to support fans, but stuff starts getting shaky when I give the green light for people to start making money off of aspects of my intellectual property. Raises questions of ownership, partnership, can lead to confusion of the origin of stuff, possibly closes doors to potential deals, etc.<br />
					It gets tricky here because the case is so minor (It's basically just the classification system and associated powers), so it's very borderline.<br />
					A note on the bottom of a given page that reads something like, 'The Futhark Generator is used to create powers that would be fitting to Wildbow's web serial Worm. Classifications, story, characters, and other elements are his by right, we're just playing in his sandbox.' would go a long way toward alleviating my concerns, and I'd be okay with the donation button then, for maintaining server costs.
				</pre>
			<p>If you're interested in how the money is being used (and what this really costs), drop me a line on reddit (<a href="https://www.reddit.com/message/compose/?to=farfromunique" target="_blank">farfromunique</a>) and I'll be happy to give you a breakdown.</p>
			<p>Thanks for visiting!</p>
			<p>Aaron C / FarFromUnique</p>

		</div>
		<div id="addedData" style="display: none;"></div>
		<div class="footer">
			<p>Legal Stuff:</p>
			<p>The Futhark Generator is used to create powers that would be fitting to Wildbow's web serial Worm. Classifications, story, characters, and other elements are his by right, we're just playing in his sandbox. For more information, click <a href="/credits">here</a>.</p>
		</div>
		<div id="loader" class="fullscreen" style="display:none;">
			<svg class="circular">
				<circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="4" stroke-miterlimit="20"/>
			</svg>
		</div>
	</body>
    <script src="/js/jquery-3.2.0.js"></script>
	<script src="/js/intercooler-1.1.1.min.js"></script>
	<script src="/js/ajax.js"></script>
</html>
