<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<title><?php echo $title ?></title>

		<!-- Bootstrap -->
		<link rel="stylesheet" href="/css/basic.css" type="text/css">
		<link rel="stylesheet" href="/css/loader.css" type="text/css">
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
		<script>
			!function(f,u,t,h,a,r,k){f.GoogleAnalyticsObject=t;f[t]||(f[t]=function(){
			(f[t].q=f[t].q||[]).push(arguments)});f[t].l=+new Date;r=u.createElement(h);
			k=u.getElementsByTagName(h)[0];r.src=a;k.parentNode.insertBefore(r,k)}
			(window,document,'ga','script','//www.google-analytics.com/analytics.js');
		</script>

		<script src="/js/analytics.js"></script>

	</head>
	<body>
		<div class='headBar'>
			<h1>Futhark Generator</h1>
			<h2><?php echo $version; ?></h2>
		</div>
		<div class='navbar'>
			<div class="navgroup">
				<p><strong>Pages here</strong></p>
				<ul>
					<li>
						<a href="/">
							Roll them bones!
						</a>
					</li>
					<li>
						<a href="/list">
							See all combinations
						</a>
					</li>
					<li>
						<a href="/donate">
							Help keep the site going
						</a>
					</li>
				</ul>
			</div>
			<div class="navgroup">
				<p><strong>Pages elsewhere</strong></p>
				<ul>
					<li>
						<a href="http://www.reddit.com/r/FutharkGenerator/">
							/r/FutharkGenerator
						</a>
					</li>
					<li>
						<a href="http://www.reddit.com/r/FutharkGenerator/comments/35fcg7/php_futhark_generator/">
							Feedback on reddit
						</a>
					</li>
					<li>
						<a href="https://github.com/farfromunique/Generator-1.5/issues/new">
							Feedback on GitHub
						</a>
					</li>
				</ul>
			</div>
			<div class="navgroup">
				Have you heard of <a href="http://parahumans.wordpress.com/">Worm</a>?
				<br />If not, please <a href="http://www.reddit.com/r/FutharkGenerator/comments/35kilh/if_you_havent_read_worm_read_me_first/">read me first!</a>
			</div>
			<div id='hist' class='hist'>
				<span id='endOfHist'>&nbsp;</span>
			</div>
		</div>
		<div class="content" id="content">
			<p>Your Roll: <button href="#" id="reroll" ic-get-from="/a/roll/" ic-target="#content">Start Over</button></p>
			<div id="bigImages" class="bigImages">
<?php for ($i=0; $i < max(count($type),count($flavor),count($twist)); $i++): ?>
				<div class="Type">
					<div title="Type: <?= $type[$i]['name']; ?>" class="Image" style="background-image:url(/img/zodiac/<?= $type[$i]['image']; ?>);"></div>
					<div class="Name"><?= $type[$i]['name']; ?></div>
					<div class="Button">
<?php if ($i == 0): ?>
						<button
						id="rollType" 
						ic-get-from="/a/roll/type" 
						ic-target="#bigImages" 
						ic-swap-style="append" 
						ic-indicator="#type-load" 
						ic-src="/a/roll/type" 
						ic-trigger-on="default" 
						ic-deps="ignore">
							Roll Another
						</button>
<?php endif; ?>
						<i id="type-load" class="lds-dual-ring"></i>
					</div>
					<input type="hidden" class="p_gen" name="type_<?= $_SERVER['REQUEST_TIME']; ?>_<?= $i; ?>" value="<?= $type[$i]['short']; ?>" />
				</div>

				<div class="Flavor">
					<div title="Flavor: <?= $flavor[$i]['name']; ?>" class="Image" style="background-image:url(/img/runes/<?= $flavor[$i]['image']; ?>);"></div>
					<div class="Name"><?= $flavor[$i]['name']; ?></div>
					<div class="Button">
<?php if ($i == 0): ?>
						<button 
						id="rollFlavor" 
						ic-get-from="/a/roll/flavor" 
						ic-target="#bigImages" 
						ic-swap-style="append" 
						ic-indicator="#flavor-load" 
						ic-src="/a/roll/flavor" 
						ic-trigger-on="default" 
						ic-deps="ignore"> 
							Roll Another
						</button>
<?php endif; ?>
						<i id="flavor-load" class="lds-dual-ring"></i>
					</div>
					<input type="hidden" class="p_gen" name="flavor_<?= $_SERVER['REQUEST_TIME']; ?>_<?= $i; ?>" value="<?= $flavor[$i]['short']; ?>" />
				</div>
				
				<div class="Twist">
					<div  title="Twist: <?= $twist[$i]['cardname']; ?>" class="Image<?= ($twist[$i]['orientation'] == 'Merkstave') ? ' reversed' : '' ?>" style="background-image:url(/img/cards/<?= $twist[$i]['image']; ?>);"></div>
					<div class="Name"><?= $twist[$i]['cardname']; ?></div>
					<div class="Button">
<?php if ($i == 0): ?>
						<button 
						id="rollTwist" 
						ic-get-from="/a/roll/twist" 
						ic-target="#bigImages" 
						ic-swap-style="append" 
						ic-indicator="#twist-load" 
						ic-src="/a/roll/twist" 
						ic-trigger-on="default" 
						ic-deps="ignore">
							Draw Again
						</button>
<?php endif; ?>
						<i id="twist-load" class="lds-dual-ring"></i>
					</div>
					<input type="hidden" class="p_gen" name="twist_<?= $_SERVER['REQUEST_TIME']; ?>_<?= $i; ?>" value="<?= $twist[$i]['short']; ?>" />
				</div>
<?php endfor; ?>
			</div>


			<div class="verboseDescription" id="Description">
<?php for ($i=0; $i < max(count($type),count($flavor),count($twist)); $i++): ?>
<?php if ($i > 0): ?>
				<hr />
<?php endif; ?>
<?php if (isset($type[$i])): ?>
				<p>You rolled the <strong><?= $type[$i]['name']; ?></strong> sign! This results in a <strong><?= $type[$i]['class']; ?></strong>-class power. <strong><?= $type[$i]['class']; ?>s</strong> have <?= $type[$i]['description']; ?></p>
<?php endif; ?>
<?php if (isset($flavor[$i])): ?>
				<p>You also rolled the <strong><?= $flavor[$i]['name']; ?></strong> rune! This results in the flavor <strong><?= $flavor[$i]['flavor']; ?></strong>, which gives a power that <?= $flavor[$i]['description']; ?>. Optionally, if your power requires an element in order to manifest, the element associated with this rune is <strong><?= $flavor[$i]['element']; ?></strong>, which roughly correlates to <?= $flavor[$i]['elementname']; ?> (but you can ignore this if it doesn't fit!).</p>
<?php endif; ?>
<?php if (isset($twist[$i])): ?>
				<p>Finally, you drew the <strong><?= $twist[$i]['cardname']; ?></strong>. <?= $twist[$i]['description']; ?></p>
<?php endif; ?>
<?php endfor; ?>
			</div>
			
			<div class="spacer"></div>
		</div>
		
		<div class="footer">
			<p>Legal Stuff:</p>
			<p>The Futhark Generator is used to create powers that would be fitting to Wildbow's web serial Worm. Classifications, story, characters, and other elements are his by right, we're just playing in his sandbox. For more information, click <a href="/credits">here</a>.</p>
		</div>
		
		<form id="keys" class="hidden">
				<input type="hidden" class="p_gen" name="default" value="probably valid" />
		</form>

	</body>
    <script src="/js/jquery-3.2.0.js"></script>
	<script src="/js/intercooler-1.1.1.min.js"></script>
	<script src="/js/ajax.js"></script>
</html>
