<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo $title ?></title>

	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="/css/bootstrap.min.css" rel="stylesheet">
	<link href="/css/base.css" rel="stylesheet">
	<link href="/css/images.css" rel="stylesheet">
	<link href="/css/loader.css" rel="stylesheet">
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

	<script>
		! function(f, u, t, h, a, r, k) {
			f.GoogleAnalyticsObject = t;
			f[t] || (f[t] = function() {
				(f[t].q = f[t].q || []).push(arguments)
			});
			f[t].l = +new Date;
			r = u.createElement(h);
			k = u.getElementsByTagName(h)[0];
			r.src = a;
			k.parentNode.insertBefore(r, k)
		}
		(window, document, 'ga', 'script', '//www.google-analytics.com/analytics.js');
	</script>

	<script src="/js/analytics.js"></script>
</head>

<body class="dark-background light-text">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-8 offset-md-2">
				<h1 class="text-center">Futhark Generator</h1>
				<h2 class="text-center subdued-text"><?php echo $version ?></h2>
				<a class="btn btn-md btn-block btn-primary mt-3 mb-0 mx-0" id="reroll" href="/">
					New Power / Reroll
				</a>
			</div>
		</div>
		<div class="row mb-3">
			<div class="col-md-8 offset-md-2 my-0">
				<?php foreach ($type as $type_) : ?>
					<div class="media mt-3 pt-2 px-2 pb-1 type dark-text">
						<img class="mr-3 ml-1 <?= $type_['short']; ?>" />
						<div class="media-body">
							<h5 class="mt-0"><?= $type_['name']; ?></h5>
							<p>You rolled the <strong><?= $type_['name']; ?></strong> sign!
								This results in a <strong><?= $type_['class']; ?></strong>-class power.
								<strong><?= $type_['class']; ?>s</strong> have <?= $type_['description']; ?>.
							</p>
						</div>
					</div>
				<?php endforeach; ?>
				<hr />
				<?php foreach ($flavor as $flavor_) : ?>
					<div class="media mt-3 pt-2 px-2 pb-1 flavor dark-text">
						<img class="mr-3 ml-1 <?= $flavor_['short']; ?>" />
						<div class="media-body">
							<h5 class="mt-0"><?= $flavor_['name']; ?></h5>
							<p>
								You threw the <strong><?= $flavor_['name']; ?></strong> rune!
								This results in the flavor <strong><?= $flavor_['flavor']; ?></strong>, which gives a power that <?= $flavor_['description']; ?>
								<br />
								<br />
								Optionally, if your power requires an element in order to manifest, the element associated with this rune is <strong><?= $flavor_['elementname']; ?></strong>, which roughly correlates to <?= $flavor_['element']; ?> (but you can ignore this if it doesn't fit!).
							</p>
						</div>
					</div>
				<?php endforeach; ?>
				<hr />
				<?php foreach ($twist as $twist_) : ?>
					<div class="media mt-3 pt-2 px-2 pb-1 twist dark-text">
						<img class="mr-3 ml-1 <?= $twist_['class']; ?>" />
						<div class="media-body">
							<h5 class="mt-0"><?= $twist_['cardname']; ?></h5>
							<p>
								<?= $twist_['description']; ?>
							</p>
						</div>
					</div>
				<?php endforeach; ?>
			</div>
		</div>
	</div>
	</div>
	</div>
	<footer class="footer">
		<div class="card text-center">
			<div class="card-footer text-muted small">
				<strong>Legal Stuff</strong>:
				<br />The Futhark Generator is used to create powers that would be fitting to Wildbow's web serial <a href="https://parahumans.wordpress.com/">Worm</a>.
				<br />Classifications, story, characters, and other elements are his by right, we're just playing in his sandbox. For more information, <a href="/credits">click here</a>.
				<br />This site uses tracking technologies to find out how many people have visited, and what they did, etc.
				<br />It also saves what you input in the fields, when you hit save.
			</div>
		</div>
	</footer>

</body>

<script src="/js/jquery-3.2.0.js"></script>
<script src="/js/intercooler-1.1.1.min.js"></script>
<script src="/js/ajax.js"></script>
<script>
	/* Set up localstorage for initially generated power */
	let store = window.localStorage;
	store.clear();
	<?php foreach ($localVars as $key => $value) : ?>
		store.setItem('<?= $key ?>', '<?= $value ?>');
	<?php endforeach; ?>
</script>

</html>