<div class="media mt-1 pt-1 twist">
	<img class="mr-3 ml-1 my-1 <?= $twist[0]['class']; ?>" />
	<div class="media-body">
		<h5 class="mt-0"><?= $twist[0]['cardname']; ?></h5>
		<p>
			<?= $twist[0]['description']; ?>
		</p>
	</div>
	<div class="icon remove" ic-action-target="closest .media" ic-action="remove">
		<svg width="20" height="20">
			<use href="#icon-delete" width="20" height="20" />
		</svg>
	</div>
</div>