<?php
	$contributors = [
		[
			'name' => 'Wildbow',
			'for' => 'tons of amazing stuff, including but not limited to being the creative mastermind behind Worm, everything Parahumans, and the power classification system used by this generator. Classifications, story, characters, and other elements are his by right, we\'re just playing in his sandbox.',
			'link' => ''
		],
		[
			'name' => '/u/ughzubat',
			'for' => 'coordination, images, descriptions, and mechanics and so much more.',
			'link' => ''
		],
		[
			'name' => '/u/TELL_ME_TO_CALM_DOWN',
			'for' => 'unflipping tables.',
			'link' => ''
		],
		[
			'name' => '/u/DrOlot',
			'for' => 'Tarot Card usage and concepts.',
			'link' => ''
		],
		[
			'name' => 'Aaron C',
			'for' => 'backend code.',
			'link' => ''
		],
		[
			'name' => '/u/Brutusness',
			'for' => 'looking at stuff and saying \"neat\".',
			'link' => ''
		],
		[
			'name' => '/u/misterspokes',
			'for' => 'merkstave rune information. Also stufff and or junk.',
			'link' => ''
		],
		[
			'name' => '/u/GreatWyrmGold',
			'for' => 'various ideas for cards, runes, etc.',
			'link' => ''
		]
	]
?>
<h2>Credits</h2>
<p>This is a creative work with many contributors. Special thanks go out to the following, for their efforts:</p>
<ul>
	<?php
		foreach ($contributors as $key) {
			echo '<li>' . $key['name'] . ' for ' . $key['for'] . '</td>.';
		}
	?>

	<p>Poker card images were generated by Aaron Coquet from a standard font and images found online. If you are the creator, please contact me!</p>
	<p>Major and Minor Arcana images are pulled from Wikipedia, and are part of the <a href="https://en.wikipedia.org/wiki/Rider-Waite_tarot_deck">Rider-Waite tarot deck</a>. Per the Wikipedia page, this work is Copyright &copy; 1910 in the United kingdom and European Union, but is Public Domain in the United States.</p>

</ul>
